apiVersion: v1
kind: ServiceAccount
metadata:
  name: accelbench-model
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "accelbench.labels" . | nindent 4 }}
    app.kubernetes.io/component: model
