apiVersion: batch/v1
kind: CronJob
metadata:
  name: accelbench-catalog-refresh
  namespace: accelbench
  labels:
    app.kubernetes.io/name: accelbench
    app.kubernetes.io/component: catalog-refresh
spec:
  schedule: "0 2 * * 0"  # Weekly: Sunday at 02:00 UTC
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      backoffLimit: 1
      ttlSecondsAfterFinished: 86400
      template:
        metadata:
          labels:
            app.kubernetes.io/name: accelbench
            app.kubernetes.io/component: catalog-refresh
        spec:
          restartPolicy: Never
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                  - matchExpressions:
                      - key: accelbench/node-type
                        operator: In
                        values:
                          - system
          containers:
            - name: seed
              image: ghcr.io/accelbench/tools:latest
              command: ["/bin/bash", "/scripts/seed-catalog.sh"]
              env:
                - name: API_URL
                  value: "http://accelbench-api.accelbench.svc.cluster.local:8080"
                - name: HF_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: accelbench-hf-token
                      key: token
                      optional: true
              volumeMounts:
                - name: scripts
                  mountPath: /scripts
                  readOnly: true
              resources:
                requests:
                  cpu: "500m"
                  memory: "256Mi"
                limits:
                  cpu: "1"
                  memory: "512Mi"
          volumes:
            - name: scripts
              configMap:
                name: accelbench-catalog-scripts
